### ISSUE TITLE
Formatting error

### ISSUE THREAD

**Issue by OxMarco** [r3nt0n/torDDoS#1]
The script fails with:
```
File "torddos.py", line 19
    print u'{}[!]{} Tor is not installed. Exiting...' .format(color.RED, color.END)
                                                                         ^
SyntaxError: invalid syntax
```

**Comment by r3nt0n** [comment]
Hello,

In the log you provide, the space between `Exiting...'` and `.format` shouldn't exists. If you check the repository, in the code there isn't any space

![imagen](https://user-images.githubusercontent.com/25709767/84916649-9e0abc80-b0be-11ea-8d00-49ef8d139ec0.png)


and it runs fine to me. Make sure you didn't make any changes in the original source. You can clone it again from github.

**Comment by wewaeaweaw** [comment]
the problem is that only work in linux. i also try in windows and get the same error.
