### ISSUE TITLE
Error: supported proxy scheme socks5

### ISSUE THREAD

**Issue by drxox** [r3nt0n/torDDoS#5]
How to selve this error?

supported proxy scheme socks5<type 
'exceptions.Exception'>

**Comment by deathpoint111** [comment]
so many errors.

**Comment by r3nt0n** [comment]
Please @sherman2000 can you provide more info about your environment in order to reproduce the error? Related to the other issue that you have opened regarding installation (#4), if you don't have tor service installed, it could be an expected behaviour

**Comment by r3nt0n** [comment]
I'm closing it, if the issue persist after tor installation (instructions in #4), please provide some info about the environment you are using (OS and python version at least).
